//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirementPerClassification
    {
        public int RequirementPerClassificationId { get; set; }
        public string RequirementId { get; set; }
        public string BusinessClassificationId { get; set; }
    }
}
