//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReg
    {
        public int Userid { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string UserPassword { get; set; }
        public string UserRePassword { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string imgname { get; set; }
        public string imgext { get; set; }
        public string imgpath { get; set; }
        public string AccountRole { get; set; }
        public bool EmailConfirmed { get; set; }
    }
}
